language: go
go:
  - 1.1.2
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - git submodule update --init --recursive

install:
  - export GOPATH=$HOME/gopath/src/github.com/cloudfoundry/hm-workspace
  - mkdir -p $GOPATH/bin
  - gem install eventmachine -v 0.12.10
  - gem install thin -v 1.4.1
  - gem install nats -v 0.4.28
  - go install -v github.com/onsi/ginkgo/ginkgo
  - pushd ./src/github.com/coreos/etcd
  - ./build
  - mv ./etcd $GOPATH/bin
  - popd
  - mkdir -p $HOME/bin
  - pushd $HOME/bin
  - curl -C - http://apache.osuosl.org/zookeeper/zookeeper-3.4.5/zookeeper-3.4.5.tar.gz | tar -zx
  - mv $HOME/bin/zookeeper-3.4.5 $HOME/bin/zookeeper
  - chmod a+x $HOME/bin/zookeeper/bin/zkServer.sh
  - curl -C - http://apache.osuosl.org/cassandra/2.0.2/apache-cassandra-2.0.2-bin.tar.gz | tar -zx
  - mv $HOME/bin/apache-cassandra-2.0.2 $HOME/bin/cassandra
  - chmod a+x $HOME/bin/cassandra/bin/cassandra
  - mkdir -p /var/log/cassandra
  - mkdir -p /var/lib/cassandra
  - popd

script:
  - export GOPATH=$HOME/gopath/src/github.com/cloudfoundry/hm-workspace
  - export PATH=$HOME/bin/cassandra/bin:$HOME/bin/zookeeper/bin:$GOPATH/bin:$PATH 
  - cd $GOPATH/src/github.com/cloudfoundry/hm9000
  - ginkgo -r -i --randomizeAllSpecs --failOnPending --skipMeasurements